application: verse-protocol
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin.*
  script: adminPanel.py
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript

- url: /.*
  script: main.py
