application: verse-protocol
version: 1
runtime: python
api_version: 1

handlers:
- url: /admin.*
  script: adminPanel.py
  login: admin

- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript

- url: /messageboard.*
  script: messageboard/handler.py

- url: /stylesheets
  static_dir: stylesheets

- url: /tasks/searchindexing.*
  script: baselibrary/handler.py
  
- url: /.*
  script: main.py
